#Official image for NGINX
FROM nginx:alpine

#Expose ports
EXPOSE 80
EXPOSE 443

CMD ["/bin/sh", "-c", "\
    envsubst '${BACKEND_DOMAIN} ${BACKEND_API_URL} ${SSL_CERT_FILE} ${SSL_KEY_FILE}' \
    < /etc/nginx/conf.d/nginx-backend-server.conf.template > /etc/nginx/conf.d/default.conf && \
    nginx -g 'daemon off;'"]