services:
  backend:
    container_name: my-relationship-app-api
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
      args:
        PROJECT_NAME: MyRelationshipApp.API
    env_file:
      - ../.env.prod
    networks:
      - rp-network

  nginx:
    container_name: nginx-rp
    build:
      context: ../backend-server
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../backend-server/certs:/etc/nginx/ssl/
      - ../backend-server/nginx:/etc/nginx/conf.d/
    env_file:
      - ../.env.prod
    networks:
      - rp-network

networks:
  rp-network:
    driver: bridge