services:
  backend:
    image: my-relationship-app-backend-prod
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
      args:
        PROJECT_PATH: ./MyRelationshipApp.API
    env_file:
      - .env.prod
    ports:
      - "5000:8080"
      - "5001:8443"
    volumes:
      - ../backend/certs:/app/https:ro