services:
  frontend:
    image: my-relationship-app-client-dev
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    ports:
      - "4200:4200"
      - "4201:4201"
    volumes:
      - ../frontend:/app