services:
  backend:
    image: my-relationship-app-backend-dev
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
      args:
        PROJECT_NAME: ${PROJECT_NAME}
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
        ASPNETCORE_URLS: ${ASPNETCORE_URLS}
        CERT_PATH: ${CERT_PATH}
        CERT_KEY: ${CERT_KEY}
    ports:
      - "5000:8080"
      - "5001:8081"
    volumes:
      - ../backend/:/app
      - ../backend/certs:/app/https:ro