services:
  backend:
    image: my-relationship-app-backend-prod
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
      args:
        PROJECT_NAME: ${PROJECT_NAME}
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
        ASPNETCORE_URLS: ${ASPNETCORE_URLS}
        CERT_PATH: ${CERT_PATH}
        CERT_KEY: ${CERT_KEY}
    ports:
      - "5000:8080"
    volumes:
      - ../backend/certs:/app/https:ro